name: Extract Data
on:
  push:
    branches:
        - main

jobs:
  extract_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: show python version
        run: python --version

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas
          

      - name: Run data extraction script
        run: python Extract.py
          